language: node_js

node_js:
  - '4.2'

services:
  - mysql

addons:
  apt:
    packages:
    - graphicsmagick
env:
  NODE_ENV: 'test'

before_script:
  - mysql -e 'create database test;'

notifications:
  email:
    - alberto@wejs.org
